### ISSUE TITLE
Mismatching terraform cli verison

### ISSUE THREAD

**Issue by sagivoulu** [zenika-open-source/terraform-azure-cli#107]
The image ```zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1``` has terraform ```0.14.2``` installed, instead of ```0.14.0```.

**Comment by bgauduch** [comment]
Hello @sagivoulu 👋 

Thanks for your interest in the project and for reporting back this issue !

I tried to reproduce the described issue by followings theses exact steps:

- pull the image `zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1`:
  > Note that the exact Terraform version expected is `0.14.0-rc1`
```bash
$ docker pull zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1
release-5.1_terraform-0.14.0-rc1_azcli-2.15.1: Pulling from zenika/terraform-azure-cli
bb79b6b2107f: Already exists 
617868c046c4: Pull complete 
95476d21c321: Pull complete 
a48a06f1a095: Pull complete 
8c88a48c4a58: Pull complete 
83b3321f1561: Pull complete 
3960d3c1fe5d: Pull complete 
Digest: sha256:339c5073cfc6f0130422227f513d9d6a75f636ceedfa0b54dfb8956c8b6a9350
Status: Downloaded newer image for zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1
docker.io/zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1
```
- run the image locally:
```bash
docker container run -it --rm --mount type=bind,source="$(pwd)",target=/workspace zenika/terraform-azure-cli:release-5.1_terraform-0.14.0-rc1_azcli-2.15.1
```
- display Terraform version:
```bash
$ root@fdbb17b17bbc:/workspace# terraform version
Terraform v0.14.0-rc1

Your version of Terraform is out of date! The latest version
is 0.14.2. You can update by downloading from https://www.terraform.io/downloads.html
```

The terraform version is indeed out of date (new release coming very soon), but I do get the exact same version in the container as in the tag.

I sadly cannot reproduce the behavior your are reporting, and therefore have a few questions:
- can you repeat the exact same steps as above and see if you still have this issue ?
- did you play any command inside the container that could have updated the Terraform version installed ?

**Comment by sagivoulu** [comment]
So this was a very silly mistake... 😅 The tf version actually matches the docker image tag.

Sorry for the hassle

**Comment by bgauduch** [comment]
Absilutely no worries, better safe than sorry 🙂
