### ISSUE TITLE
add a terraform-gcp-cli

### ISSUE THREAD

**Issue by MacFlurry** [zenika-open-source/terraform-azure-cli#124]
Hello,

it would be awesome if you can add a terraform-gcp-cli image to the dockerhub also.

Thanks in advance.

Regards,

MacFlurry

**Comment by bgauduch** [comment]
Hello @MacFlurry And thanks for opening this issue 👋 

That's a great idea but I'm missing time to manage these open source projects 😅 
To create a new one would require help, would you be able to give a hand ?

Have a good day in the meantime !

**Comment by bgauduch** [comment]
Closing as not related to this repository
