### ISSUE TITLE
envsubst not available 

### ISSUE THREAD

**Issue by UteHaus** [zenika-open-source/terraform-azure-cli#126]
Hello,

it would be awesome if you can add envsubst. I need it for the deployment pipeline, to replace env variables.

**Possible solution:**
For Debian  ` apt-get install gettext-base`

Thanks.

**Comment by bgauduch** [comment]
Hello @UteHaus and thanks for your interest !

I would suggest that you build a new image upon this one that suit your need, as the goal here is to keep the image as minimalist as possible and scoped only toward Terraform and Azure CLI !

A simple way to achieve this is by using this image in the `FROM` Dockerfile argument in a new image you can build, like this:

```docker
FROM zenika/terraform-azure-cli:release-6.1_terraform-1.0.6_azcli-2.28.1
RUN  apt-get install -y --no-install-recommends gettext-base
```

Best regards !
