### ISSUE TITLE
Update terraform version.

### ISSUE THREAD

**Issue by alan-cushla** [zenika-open-source/terraform-azure-cli#130]
Ça va? 🙂 

I'm just wondering if it would be possible to get an update with a newer terraform version (and probably az-cli too)? 

If you're too busy, I'd happily do a PR if you can point me in the direction of what needs to be done.

Thanks!

**Comment by alan-cushla** [comment]
@bgauduch I've opened a PR for this [here](https://github.com/zenika-open-source/terraform-azure-cli/pull/133). If you have some time could you please take a look? Thanks. 🙂

**Comment by bgauduch** [comment]
Hello @alan-cushla 👋 

Thanks a lot for your your interest and active contribution 🙏 
I'm terribly sorry for the late answer, 'm a bit overwhelm and looking for contributors for this projects 🔭

Looking into you PR right now !

**Comment by bgauduch** [comment]
Will be closed by #136

**Comment by bgauduch** [comment]
It is done ✅ 
@alan-cushla
